import sqlite3
conn=sqlite3.connect('bus_ticket.db')
cursor=conn.cursor()
cursor.execute('create table if not exists bus(bus_id varchar(2) not null primary key,bus_type varchar(10),capacity int,fair int,op_id varchar(5) not null,route_id varchar(5) not null,foreign key(op_id) references operator(opr_id),foreign key(route_id) references route(r_id))')
cursor.execute('create table if not exists operator(opr_id varchar(5) primary key,name varchar(20),address varchar(50),phone char(10),email varchar(30))')
cursor.execute('create table if not exists running(b_id varchar(5) ,run_date date,seat_avail int,foreign key(b_id) references bus(bus_id))')
cursor.execute('create table if not exists route(r_id varchar(5) not null primary key,s_name varchar(20),s_id varchar(5),e_name varchar(20),e_id varchar(5) )')
cursor.execute('create table if not exists booking_history(name varchar(20),gender char(1),no_of_seat int,phone char(10),age int,booking_ref varchar(10) not null primary key,travel_date date,bid varchar(5),foreign key(bid) references bus(bus_id))')
cursor.execute('''SELECT * FROM bus WHERE bus_id=?''', ('1',))
existing_record = cursor.fetchone()
if not existing_record:
    cursor.execute('''INSERT INTO bus VALUES('1','AC 2x2',35,1250,'2','1')''')
    cursor.execute('''INSERT INTO bus VALUES('2','AC 2x2',45,2500,'2','2')''')
    cursor.execute('''INSERT INTO bus VALUES('3','AC 2x2',30,1800,'3','4')''')
    cursor.execute('''INSERT INTO bus VALUES('4','AC 2x2',35,1500,'1','3')''')
    cursor.execute('''INSERT INTO bus VALUES('5','AC 3x2',40,1200,'1','1')''')
    cursor.execute('''INSERT INTO bus VALUES('6','AC 3x2',30,1400,'3','2')''')
cursor.execute('''SELECT * FROM operator WHERE opr_id=?''', ('1',))
existing_rec = cursor.fetchone()
if not existing_rec:
    cursor.execute('''INSERT INTO operator VALUES('1','Kamla Travels','Indore','9876543210','kamla@gmail.com')''')
    cursor.execute('''INSERT INTO operator VALUES('2','Shatabdi Travels','Gurugram','6549873210','shatabdi@gmail.com')''')
    cursor.execute('''INSERT INTO operator VALUES('3','Hans Travels','Gwalior','7783868382','hans@gmail.com')''')
    cursor.execute('''INSERT INTO operator VALUES('4','Raj Ratan Travels','Bhopal','1234567890','raj@gmail.com')''')
    cursor.execute('''INSERT INTO operator VALUES('5','Samay Travels','Lucknow','8778877878','samay@gmail.com')''')
cursor.execute('''SELECT * FROM running''')
existing_rcrd = cursor.fetchone()
if not existing_rcrd:
    cursor.execute('''INSERT INTO running VALUES('1','2023-12-10',35)''')
    cursor.execute('''INSERT INTO running VALUES('1','2023-12-11',40)''')
    cursor.execute('''INSERT INTO running VALUES('1','2023-12-12',32)''')
    cursor.execute('''INSERT INTO running VALUES('1','2023-12-13',50)''')
    cursor.execute('''INSERT INTO running VALUES('2','2023-12-10',41)''')
    cursor.execute('''INSERT INTO running VALUES('2','2023-12-11',47)''')
    cursor.execute('''INSERT INTO running VALUES('2','2023-12-12',35)''')
    cursor.execute('''INSERT INTO running VALUES('2','2023-12-09',35)''')
    cursor.execute('''INSERT INTO running VALUES('3','2023-12-09',30)''')
    cursor.execute('''INSERT INTO running VALUES('3','2023-12-10',50)''')
    cursor.execute('''INSERT INTO running VALUES('4','2023-12-09',39)''')
    cursor.execute('''INSERT INTO running VALUES('4','2023-12-10',40)''')
    cursor.execute('''INSERT INTO running VALUES('5','2023-12-10',35)''')
    cursor.execute('''INSERT INTO running VALUES('6','2023-12-10',30)''')
cursor.execute('''SELECT * FROM route WHERE r_id=?''', ('1',))
existing_rcd = cursor.fetchone()
if not existing_rcd:
    cursor.execute(''' INSERT INTO route VALUES('1','guna','080','kanpur','078')''')
    cursor.execute(''' INSERT INTO route VALUES('2','kanpur','078','guna','080')''')
    cursor.execute(''' INSERT INTO route VALUES('3','guna','080','bhopal','003')''')
    cursor.execute(''' INSERT INTO route VALUES('4','bhopal','003','guna','080')''')
    cursor.execute(''' INSERT INTO route VALUES('5','guna','080','lucknow','004')''')
    cursor.execute(''' INSERT INTO route VALUES('6','lucknow','004','guna','080')''')
    cursor.execute(''' INSERT INTO route VALUES('7','guna','080','vadodara','029')''')
    cursor.execute(''' INSERT INTO route VALUES('8','vadodara','029','guna','080')''')
    cursor.execute(''' INSERT INTO route VALUES('9','guna','080','prayagraj','070')''')
    cursor.execute(''' INSERT INTO route VALUES('10','guna','004','delhi','011')''')
conn.commit()

conn.close()
